#!/bin/sh
set -e
# NOTE: replace 1234-ABCD with UUID of the EFI partition,
# where Syslinux is installed
cat <<EOF
if [ "\$grub_platform" = "efi" ] ; then
	menuentry 'Syslinux' \$menuentry_id_option 'syslinux' {
		insmod part_gpt
		insmod fat
		search --no-floppy --fs-uuid --set=root '1234-ABCD'
		chainloader /EFI/syslinux/syslinux.efi
	}
fi
EOF
